export { default as HeroDiagnostic } from "./HeroDiagnostic";
export { default as ProblemesDiagnostic } from "./ProblemesDiagnostic";
export { default as ParcoursDiagnostic } from "./ParcoursDiagnostic";
export { default as ElementsDiagnostic } from "./ElementsDiagnostic";
export { default as TarifDiagnostic } from "./TarifDiagnostic";
export { default as DiagnosticVsCorrection } from "./DiagnosticVsCorrection";
export { default as PreparationDiagnostic } from "./PreparationDiagnostic";
export { default as ResultatDiagnostic } from "./ResultatDiagnostic";
export { default as FaqDiagnostic } from "./FaqDiagnostic";